[[repo]]
url = "https://github.com/0xAlphaDevs/ai-nfts-mintbase"

[[repo]]
url = "https://github.com/0xlucyg/hot-wallet-auto-claim"

[[repo]]
url = "https://github.com/8790fahad/checkdrug"

[[repo]]
url = "https://github.com/aakash4dev/near_testnet_createwallet"

[[repo]]
url = "https://github.com/alanesmizi/cgapiforge"

[[repo]]
url = "https://github.com/aliveevie/near-editor-app"

[[repo]]
url = "https://github.com/alperozaydin/trade-plate"

[[repo]]
url = "https://github.com/AmaanSayyad/NJ"

[[repo]]
url = "https://github.com/andy-haynes/wigesque"

[[repo]]
url = "https://github.com/antematter/frontend-developer-test"

[[repo]]
url = "https://github.com/anyswap/anyswap-crosschain"

[[repo]]
url = "https://github.com/arizas/Ariz-Portfolio"

[[repo]]
url = "https://github.com/artdaw/skychef-webapp"

[[repo]]
url = "https://github.com/bayy420-999/hot-game"

[[repo]]
url = "https://github.com/BestCryptoKnight/Nativo-NFT-UI"

[[repo]]
url = "https://github.com/bpolania/near-scaffold"

[[repo]]
url = "https://github.com/bxdoan/pywallet"

[[repo]]
url = "https://github.com/callmediddy/near-extension-for-shopify"

[[repo]]
url = "https://github.com/danielbui12/near_sdk_practice"

[[repo]]
url = "https://github.com/Deonorla/Game_bloc_3.0"

[[repo]]
url = "https://github.com/Dictatorsnft/Game_wl_raffle_frontend"

[[repo]]
url = "https://github.com/dnbk3/Blockchain_learning"

[[repo]]
url = "https://github.com/doriancrutcher/sdk-js-docs"

[[repo]]
url = "https://github.com/dvconsultores/walletarepa_front"

[[repo]]
url = "https://github.com/electrone901/near-guest-book"

[[repo]]
url = "https://github.com/faithful1ofall/NFT-temp"

[[repo]]
url = "https://github.com/firasbelhiba/chatafisha-marketplace"

[[repo]]
url = "https://github.com/flowscience/nft-farm"

[[repo]]
url = "https://github.com/freewind-demos/typescript-webpack-near-connect-mynearwallet-demo"

[[repo]]
url = "https://github.com/frolvanya/near-lake-framework-py"

[[repo]]
url = "https://github.com/glowupmatt/near-practice"

[[repo]]
url = "https://github.com/GSL-AI/GSL"

[[repo]]
url = "https://github.com/Guid21/near-wallet"

[[repo]]
url = "https://github.com/hack-a-chain-software/jump.project"

[[repo]]
url = "https://github.com/handelmanjosh/nearcade"

[[repo]]
url = "https://github.com/hcho112/web3authn-demo"

[[repo]]
url = "https://github.com/hoanglongne/Trusify"

[[repo]]
url = "https://github.com/hydrogenbond007/tinkering"

[[repo]]
url = "https://github.com/icon-project/icon-bridge"

[[repo]]
url = "https://github.com/idea404/FT-JS"

[[repo]]
url = "https://github.com/ilerik/vself-brands"

[[repo]]
url = "https://github.com/ilovelili/near-playground"

[[repo]]
url = "https://github.com/Jabolol/packet"

[[repo]]
url = "https://github.com/jamesirez/smc-partie-team-Hackathon"

[[repo]]
url = "https://github.com/jamesirez/ui-pat"

[[repo]]
url = "https://github.com/johnedvard/js13kgames2022"

[[repo]]
url = "https://github.com/josedlujan/NEAR-sdk-kotlin"

[[repo]]
url = "https://github.com/KapokProgramming/Youchain"

[[repo]]
url = "https://github.com/kei0301/frontend"

[[repo]]
url = "https://github.com/keypom/keypom-frontend"

[[repo]]
url = "https://github.com/killswitchofficial/bos-gg"

[[repo]]
url = "https://github.com/kingpig-dev/web4"

[[repo]]
url = "https://github.com/KryptikApp/kryptikwebapp"

[[repo]]
url = "https://github.com/kurodenjiro/joydragon"

[[repo]]
url = "https://github.com/lakshz/nft-auction-contract"

[[repo]]
url = "https://github.com/leapwallet/leap-near-sdk-react-example"

[[repo]]
url = "https://github.com/LimeChain/nearjs-react-app"

[[repo]]
url = "https://github.com/ManuelenRed/Donate_to_artists_NEAR"

[[repo]]
url = "https://github.com/MarmaJFoundation/pixeldapps-contract"

[[repo]]
url = "https://github.com/MasteraSnackin/coin-flip"

[[repo]]
url = "https://github.com/metaguild/near-wiki"

[[repo]]
url = "https://github.com/Mintbase/near-ca"

[[repo]]
url = "https://github.com/mr-harshtyagi/ai-nfts"

[[repo]]
url = "https://github.com/muhammedalibilgin/order-management-with-near2"

[[repo]]
url = "https://github.com/nadabots/nadabot-docs"

[[repo]]
url = "https://github.com/nategeier/me-markets"

[[repo]]
url = "https://github.com/ndxbinh1922001/Rabbit_OnChain"

[[repo]]
url = "https://github.com/near-examples/coin-flip-examples"

[[repo]]
url = "https://github.com/near-examples/counter-js-deprecated"

[[repo]]
url = "https://github.com/near-examples/guest-book-rust-deprecated"

[[repo]]
url = "https://github.com/near-ndc/voting-v2"

[[repo]]
url = "https://github.com/NEARBuilders/monorepo"

[[repo]]
url = "https://github.com/Nityam573/NFT-NEAR"

[[repo]]
url = "https://github.com/OlegMakarenko/near2-hackathon-contract"

[[repo]]
url = "https://github.com/Onihani/PeerTrade"

[[repo]]
url = "https://github.com/ozo-vehe/auctioneer"

[[repo]]
url = "https://github.com/Pessina/near-sandbox"

[[repo]]
url = "https://github.com/petarvujovic98/blockraise"

[[repo]]
url = "https://github.com/piordev555/Front-End-starter_Tenk_Dao"

[[repo]]
url = "https://github.com/piordev555/web-dapp-near"

[[repo]]
url = "https://github.com/PolpEdu/testdeploy"

[[repo]]
url = "https://github.com/PowderDev/near-service"

[[repo]]
url = "https://github.com/pvolnov/py-near"

[[repo]]
url = "https://github.com/roke-to/roketo-business-ui"

[[repo]]
url = "https://github.com/roshaans/AddFAKWarningTest"

[[repo]]
url = "https://github.com/sandoche/NEARwrite"

[[repo]]
url = "https://github.com/schoolofacceleratedlearning/xtoearn-sdk-examples"

[[repo]]
url = "https://github.com/seetadev/PolyOps"

[[repo]]
url = "https://github.com/sgarcia22/litmus"

[[repo]]
url = "https://github.com/shelegdmitriy/rust-smart-contract-test-project"

[[repo]]
url = "https://github.com/shipsgold/multi-token-standard-impl"

[[repo]]
url = "https://github.com/smidhonza/near-contract-test"

[[repo]]
url = "https://github.com/solecnugit/PoCo"

[[repo]]
url = "https://github.com/stream-protocol/wallet"

[[repo]]
url = "https://github.com/SudeepGowda55/daily-art-battle"

[[repo]]
url = "https://github.com/svntax/gamedevjs-jam-2022"

[[repo]]
url = "https://github.com/tamermint/repticle"

[[repo]]
url = "https://github.com/thamerdridi/DAO-On-Near"

[[repo]]
url = "https://github.com/The-Blockbuster/buster-cli"

[[repo]]
url = "https://github.com/thisisjoshford/repo-reports"

[[repo]]
url = "https://github.com/TrevorJTClarke/vue-near"

[[repo]]
url = "https://github.com/urbit/NearSocialVM"

[[repo]]
url = "https://github.com/vishalisharm/near-wallet"

[[repo]]
url = "https://github.com/wormhole3/wormhole3-account-binding"

[[repo]]
url = "https://github.com/Xaxis/near-sdk-js-learnings"

[[repo]]
url = "https://github.com/xem/gamedevjs2022"