# Ecosystem Level Information for Vanity ETH Generator Poly
title = "Vanity ETH Generator Poly"

# Assuming Vanity ETH Generator Poly is compatible with certain chains, list them here.
# Replace these with the actual compatible chains.
sub_ecosystems = ["Ethereum", "Binance Smart Chain", "Polygon", "zkSync", "zkSync Era", "Scroll]

# GitHub organization URL - Adjust this based on whether it's an organization or a project.
github_organizations = ["https://github.com/samaeleth"]

# Repositories
[[repo]]
url = "https://github.com/samaeleth/vanity-eth-generator"
