# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Generate hash of core files
        id: hash
        run: |
          echo "files_hash=$(find . -maxdepth 2 -name "run.sh" -o -path "./src/*" \( -name "*.zig" -o -name "*.sh" \) | sort | xargs sha1sum | sha1sum | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

      - name: Cache build artifacts
        id: cache
        uses: actions/cache@v3
        with:
          path: zig-out/bin/ce
          key: ${{ runner.os }}-build-${{ steps.hash.outputs.files_hash }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ./run.sh build
          ./run.sh test

      - name: Validate Migrations from Genesis
        run: |
          ./zig-out/bin/ce validate
