name: Crypto commits

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Make 600 commits
      run: |
        for i in {1..600}
        do
          echo "Modification $i" >> fichier.txt
          git add fichier.txt
          git commit -m "Commit numéro $i"
        done
    
    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
